### ISSUE TITLE
Support multiline entries

### ISSUE THREAD

**Issue by SBoudrias** [npm/ini#33]
It'd be great to have multiline support:

``` ini
commands = 
    pylint
    coverage run -m pytest
```

**Comment by HillLiu** [comment]
+1

**Comment by KernelDeimos** [comment]
Multi-line support descried [on Wikipedia](https://en.wikipedia.org/wiki/INI_file#cite_note-multiline-entry-13) and seen in systemd unit files involves using backslashes to escape new lines.

(that said, it's actually unclear which of these two conventions systemd is following - I see it in a string being passed to `sh -c` so it could be being processed be either...)

Well, if I look at the standard then...

oh...

so it seems like where in [this situation](https://xkcd.com/927/), fantastic.

My suggestion is to allow both types of multiline string and require this to be configured, because that would make this package useful for a wider variety of ini files.

**Comment by wraithgar** [comment]
If this is still something folks need feel free to submit a PR implementing the feature.

**Comment by pgalbraith** [comment]
> If this is still something folks need feel free to submit a PR implementing the feature.

@wraithgar this is exactly what I did, can you comment?
